apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo
  description: demo
  annotations:
    backstage.io/techdocs-ref: dir:./
spec:
  type: documentation
  owner: microservice
  lifecycle: experimental