---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-teams
  description: demo
  annotations:
    backstage.io/techdocs-ref: dir:./
spec:
  type: documentation
  owner: microservice
  lifecycle: experimental
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Devops
  description: Devops Team
  annotations:
    backstage.io/techdocs-ref: dir:./portal1
spec:
  type: documentation
  owner: Devops
  lifecycle: experimental
  subcomponentOf: demo-teams
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Microservices
  description: Microservices Team
  annotations:
    backstage.io/techdocs-ref: dir:./portal2
spec:
  type: documentation
  owner: microservice
  lifecycle: experimental
  subcomponentOf: demo-teams
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Frontdoor
  description: Team under Developer
  annotations:
    backstage.io/techdocs-ref: dir:./portal1/child1/
spec:
  type: documentation
  owner: frontdoor
  lifecycle: experimental
  subcomponentOf: Microservices